version: '3.7'

services:

  # The application
  stripe:
    build:
      context: .
    restart: always
    image: &stripe stripe
    container_name: stripe
    ports:
      - 8000:8000
    volumes:
      - ./stripe:/stripe
    env_file:
      - .env
    command:
      python manage.py runserver 0.0.0.0:8000
    links:
      - postgres
    depends_on:
      - postgres

  # Database
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
